"""Add signature paths to VehicleHandover

Revision ID: 0fa049d9d475
Revises: d2acb7d61f1c
Create Date: 2025-06-18 05:01:56.268885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa049d9d475'
down_revision = 'd2acb7d61f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_signature_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('driver_signature_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.drop_column('driver_signature_path')
        batch_op.drop_column('supervisor_signature_path')

    # ### end Alembic commands ###
