"""Add Nationality and link to Employee (named constraint)

Revision ID: 26ff27de62e6
Revises: 8a3c9d83d0e0
Create Date: 2025-06-28 02:11:44.069912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ff27de62e6'
down_revision = '8a3c9d83d0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_employee')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobilePersonal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nationality_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('license_status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_employee_nationality_id', 'nationalities', ['nationality_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_nationality_id', type_='foreignkey')
        batch_op.drop_column('license_status')
        batch_op.drop_column('contract_status')
        batch_op.drop_column('nationality_id')
        batch_op.drop_column('mobilePersonal')

    op.create_table('_alembic_tmp_employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('national_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('project', sa.VARCHAR(length=100), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('join_date', sa.DATE(), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contract_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('basic_salary', sa.FLOAT(), nullable=True),
    sa.Column('has_national_balance', sa.BOOLEAN(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('national_id_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('license_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('mobilePersonal', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nationality_id', sa.INTEGER(), nullable=True),
    sa.Column('contract_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('license_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationalities.id'], name=op.f('fk_employee_nationality_id')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('national_id')
    )
    # ### end Alembic commands ###
