"""11111111111111111

Revision ID: 45b120160799
Revises: 26ff27de62e6
Create Date: 2025-06-28 05:18:43.563228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b120160799'
down_revision = '26ff27de62e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handover_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supervisor_employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_car_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vehicle_plate_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vehicle_model_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('driver_company_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('driver_phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('driver_residency_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('driver_contract_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('driver_license_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supervisor_company_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supervisor_phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('supervisor_residency_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supervisor_contract_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supervisor_license_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reason_for_change', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_status_summary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reason_for_authorization', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('authorization_details', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('movement_officer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('movement_officer_signature_path', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_handover_supervisor_employee_id', 'employee', ['supervisor_employee_id'], ['id'])
        batch_op.drop_column('vehicle_condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_condition', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('fk_handover_supervisor_employee_id', type_='foreignkey')
        batch_op.drop_column('movement_officer_signature_path')
        batch_op.drop_column('movement_officer_name')
        batch_op.drop_column('authorization_details')
        batch_op.drop_column('reason_for_authorization')
        batch_op.drop_column('vehicle_status_summary')
        batch_op.drop_column('reason_for_change')
        batch_op.drop_column('supervisor_license_status')
        batch_op.drop_column('supervisor_contract_status')
        batch_op.drop_column('supervisor_residency_number')
        batch_op.drop_column('supervisor_phone_number')
        batch_op.drop_column('supervisor_company_id')
        batch_op.drop_column('driver_license_status')
        batch_op.drop_column('driver_contract_status')
        batch_op.drop_column('driver_residency_number')
        batch_op.drop_column('driver_phone_number')
        batch_op.drop_column('driver_company_id')
        batch_op.drop_column('vehicle_model_year')
        batch_op.drop_column('vehicle_plate_number')
        batch_op.drop_column('vehicle_car_type')
        batch_op.drop_column('supervisor_employee_id')
        batch_op.drop_column('city')
        batch_op.drop_column('project_name')
        batch_op.drop_column('handover_time')

    # ### end Alembic commands ###
