"""Add checklist fields to HandoverRecord

Revision ID: 61750b3ef6f5
Revises: 
Create Date: 2025-06-18 01:33:50.482252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61750b3ef6f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_oil_leaks', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_gear_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_clutch_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_engine_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_windows_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_tires_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_body_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_electricity_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_lights_issue', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_ac_issue', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.drop_column('has_ac_issue')
        batch_op.drop_column('has_lights_issue')
        batch_op.drop_column('has_electricity_issue')
        batch_op.drop_column('has_body_issue')
        batch_op.drop_column('has_tires_issue')
        batch_op.drop_column('has_windows_issue')
        batch_op.drop_column('has_engine_issue')
        batch_op.drop_column('has_clutch_issue')
        batch_op.drop_column('has_gear_issue')
        batch_op.drop_column('has_oil_leaks')

    # ### end Alembic commands ###
