"""Add custom report branding to VehicleHandover

Revision ID: 641a94454573
Revises: 0fa049d9d475
Create Date: 2025-06-18 05:54:11.029812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641a94454573'
down_revision = '0fa049d9d475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('report_logo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.drop_column('report_logo_path')
        batch_op.drop_column('report_company_name')

    # ### end Alembic commands ###
