"""Implement many-to-many relationship for employees and departments

Revision ID: 8a3c9d83d0e0
Revises: b685fec77b15
Create Date: 2025-06-20 02:29:44.856222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3c9d83d0e0'
down_revision = 'b685fec77b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
