"""empty message

Revision ID: c0f8ead8d439
Revises: 641a94454573
Create Date: 2025-06-18 06:37:01.913053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f8ead8d439'
down_revision = '641a94454573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_logo_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('report_company_name')
        batch_op.drop_column('report_logo_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_logo_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('report_company_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('custom_logo_path')
        batch_op.drop_column('custom_company_name')

    # ### end Alembic commands ###
