"""empty message

Revision ID: c8881a3d88d9
Revises: c0f8ead8d439
Create Date: 2025-06-18 06:41:16.755533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8881a3d88d9'
down_revision = 'c0f8ead8d439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.drop_column('custom_logo_path')
        batch_op.drop_column('custom_company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_company_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_logo_path', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
