"""Add damage_diagram_path to VehicleHandover

Revision ID: d2acb7d61f1c
Revises: 61750b3ef6f5
Create Date: 2025-06-18 04:01:12.272090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2acb7d61f1c'
down_revision = '61750b3ef6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_diagram_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.drop_column('damage_diagram_path')

    # ### end Alembic commands ###
