"""empty message

Revision ID: fc4ccae59f02
Revises: c8881a3d88d9
Create Date: 2025-06-18 06:41:57.830398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4ccae59f02'
down_revision = 'c8881a3d88d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_logo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_handover', schema=None) as batch_op:
        batch_op.drop_column('custom_logo_path')
        batch_op.drop_column('custom_company_name')

    # ### end Alembic commands ###
